version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    container_name: fx_timescaledb
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: trading
      POSTGRES_USER: trading_user
      POSTGRES_PASSWORD: trading_pass_2024
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    command:
      - postgres
      - -c
      - shared_preload_libraries=timescaledb
      - -c
      - max_connections=200
      - -c
      - work_mem=16MB
      - -c
      - maintenance_work_mem=256MB
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U trading_user -d trading"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  timescaledb_data:
    driver: local

networks:
  default:
    name: fx_trading_network
