-- ============================================================================
-- Migration 019: Recreate Trading Tables for TradingPersistenceService
-- Date: 2025-11-08
-- Purpose: Re-create orders/positions/strategy_signals tables dropped in migration 003
--
-- CRITICAL SCHEMA CONFLICT RESOLUTION:
-- Migration 003 dropped these tables with comment "not used in current codebase"
-- However, TradingPersistenceService (src/domain/services/trading_persistence.py)
-- REQUIRES these tables for ALL trading modes (live/paper/backtest).
--
-- RESULT: Runtime INSERT failures when TradingPersistenceService is wired to EventBus
--
-- SOLUTION: Re-create tables with IMPROVED schema based on:
--   1. Original schema from migration 001
--   2. TradingPersistenceService INSERT requirements
--   3. QuestDB best practices (DEDUP, SYMBOL, WAL, partitioning)
--
-- Tables recreated:
--   1. strategy_signals - Trading signal history (S1, Z1, ZE1, E1, O1, EMERGENCY)
--   2. orders - Order execution tracking (NEW, FILLED, PARTIALLY_FILLED, CANCELLED)
--   3. positions - Position tracking with P&L (OPEN, CLOSED, LIQUIDATED)
--
-- Improvements over migration 001:
--   - Added session_id for backtesting correlation (consistency with other tables)
--   - Added signal_id to strategy_signals for unique identification
--   - Improved deduplication keys (UPSERT mode for idempotency)
--   - Enhanced SYMBOL usage for performance
--   - IF NOT EXISTS for migration idempotency
-- ============================================================================


-- ============================================================================
-- 1. STRATEGY_SIGNALS TABLE
-- ============================================================================
-- Stores strategy signals (S1, S2, Z1, ZE1, E1, O1, EMERGENCY) generated by strategy evaluator
-- Used by: TradingPersistenceService._on_signal_generated()
-- Event: signal_generated
--
-- Expected volume: ~1,000 rows/day per active strategy
--
-- IMPROVEMENTS over migration 001:
--   - Added session_id: Links signals to data collection sessions (backtesting support)
--   - Added signal_id: Unique identifier for each signal (enables proper DEDUP)
--   - DEDUP keys: (timestamp, signal_id) for idempotent inserts
--
-- TradingPersistenceService INSERT (lines 225-250):
--   INSERT INTO strategy_signals (
--       strategy_id, symbol, signal_type, timestamp, triggered,
--       conditions_met, indicator_values, action, metadata
--   ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)

DROP TABLE IF EXISTS strategy_signals;

CREATE TABLE IF NOT EXISTS strategy_signals (
    -- Identifiers
    signal_id STRING,                           -- Unique signal identifier (NEW: for DEDUP)
    strategy_id SYMBOL capacity 512 CACHE,      -- Strategy that generated signal
    symbol SYMBOL capacity 256 CACHE,           -- Trading pair (BTC_USDT, ETH_USDT, etc.)
    session_id SYMBOL capacity 2048 CACHE,      -- Link to data_collection_sessions (NEW: for backtesting)

    -- Signal data
    signal_type SYMBOL capacity 64 CACHE,       -- Signal type: S1, S2, Z1, ZE1, E1, O1, EMERGENCY
    timestamp TIMESTAMP,                         -- Signal generation timestamp
    triggered BOOLEAN,                           -- Whether signal was triggered (true/false)
    action STRING,                               -- Action taken: BUY, SELL, CANCEL, CLOSE

    -- Context (JSON strings)
    conditions_met STRING,                       -- JSON: which conditions were met
    indicator_values STRING,                     -- JSON: indicator values at signal time
    metadata STRING                              -- JSON: additional metadata

) timestamp(timestamp) PARTITION BY DAY WAL
DEDUP UPSERT KEYS(timestamp, signal_id);

-- Performance notes:
--   - SYMBOL types (strategy_id, symbol, session_id, signal_type) are auto-indexed
--   - PARTITION BY DAY enables efficient time-based queries and cleanup
--   - DEDUP on (timestamp, signal_id) prevents duplicate signal inserts
--   - WAL ensures durability and enables DEDUP


-- ============================================================================
-- 2. ORDERS TABLE
-- ============================================================================
-- Stores order lifecycle (created, filled, cancelled)
-- Used by: TradingPersistenceService._on_order_created/filled/cancelled()
-- Events: order_created, order_filled, order_cancelled
--
-- Expected volume: ~100 rows/day per active strategy
--
-- IMPROVEMENTS over migration 001:
--   - Added session_id: Links orders to data collection sessions (backtesting support)
--   - DEDUP keys: (timestamp, order_id) for idempotent inserts
--
-- TradingPersistenceService INSERT (lines 313-347):
--   INSERT INTO orders (
--       order_id, strategy_id, symbol, side, order_type, timestamp,
--       quantity, price, filled_quantity, filled_price, status, commission, metadata
--   ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)

DROP TABLE IF EXISTS orders;

CREATE TABLE IF NOT EXISTS orders (
    -- Identifiers
    order_id SYMBOL capacity 4096 CACHE,        -- Exchange order ID (unique per order)
    strategy_id SYMBOL capacity 512 CACHE,      -- Strategy that created order
    symbol SYMBOL capacity 256 CACHE,           -- Trading pair
    session_id SYMBOL capacity 2048 CACHE,      -- Link to data_collection_sessions (NEW: for backtesting)

    -- Order parameters
    side SYMBOL capacity 8 CACHE,               -- BUY or SELL
    order_type SYMBOL capacity 16 CACHE,        -- MARKET, LIMIT, STOP_LOSS, etc.
    timestamp TIMESTAMP,                         -- Order creation timestamp
    quantity DOUBLE,                             -- Order quantity
    price DOUBLE,                                -- Order price (null for MARKET orders)

    -- Execution details
    filled_quantity DOUBLE,                      -- Filled quantity (0.0 initially)
    filled_price DOUBLE,                         -- Average filled price (null until filled)
    status SYMBOL capacity 32 CACHE,            -- NEW, FILLED, PARTIALLY_FILLED, CANCELLED
    commission DOUBLE,                           -- Trading commission (0.0 initially)

    -- Metadata
    metadata STRING                              -- JSON: additional order metadata

) timestamp(timestamp) PARTITION BY DAY WAL
DEDUP UPSERT KEYS(timestamp, order_id);

-- Performance notes:
--   - SYMBOL types (order_id, strategy_id, symbol, session_id, side, order_type, status) are auto-indexed
--   - PARTITION BY DAY enables efficient time-based queries
--   - DEDUP on (timestamp, order_id) prevents duplicate order inserts
--   - UPDATE queries (order_filled, order_cancelled) modify status and fill data


-- ============================================================================
-- 3. POSITIONS TABLE
-- ============================================================================
-- Stores position snapshots (entry, updates, exit)
-- Used by: TradingPersistenceService._on_position_opened/updated/closed()
-- Events: position_opened, position_updated, position_closed
--
-- Expected volume: ~50 rows/day per active strategy
--
-- IMPROVEMENTS over migration 001:
--   - Added session_id: Links positions to data collection sessions (backtesting support)
--   - DEDUP keys: (timestamp, position_id) for idempotent inserts
--
-- TradingPersistenceService INSERT (lines 492-528):
--   INSERT INTO positions (
--       position_id, strategy_id, symbol, timestamp, side,
--       quantity, entry_price, current_price, unrealized_pnl, realized_pnl,
--       stop_loss, take_profit, status, metadata
--   ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)

DROP TABLE IF EXISTS positions;

CREATE TABLE IF NOT EXISTS positions (
    -- Identifiers
    position_id SYMBOL capacity 4096 CACHE,     -- Position identifier (unique per position)
    strategy_id SYMBOL capacity 512 CACHE,      -- Strategy that opened position
    symbol SYMBOL capacity 256 CACHE,           -- Trading pair
    session_id SYMBOL capacity 2048 CACHE,      -- Link to data_collection_sessions (NEW: for backtesting)

    -- Position details
    timestamp TIMESTAMP,                         -- Position event timestamp
    side SYMBOL capacity 8 CACHE,               -- LONG or SHORT
    quantity DOUBLE,                             -- Position size

    -- Price tracking
    entry_price DOUBLE,                          -- Entry price
    current_price DOUBLE,                        -- Current market price

    -- P&L tracking
    unrealized_pnl DOUBLE,                       -- Unrealized profit/loss (0.0 initially)
    realized_pnl DOUBLE,                         -- Realized profit/loss (0.0 until closed)

    -- Risk management
    stop_loss DOUBLE,                            -- Stop loss price (null if not set)
    take_profit DOUBLE,                          -- Take profit price (null if not set)

    -- Status
    status SYMBOL capacity 32 CACHE,            -- OPEN, CLOSED, LIQUIDATED

    -- Metadata
    metadata STRING                              -- JSON: additional position metadata

) timestamp(timestamp) PARTITION BY DAY WAL
DEDUP UPSERT KEYS(timestamp, position_id);

-- Performance notes:
--   - SYMBOL types (position_id, strategy_id, symbol, session_id, side, status) are auto-indexed
--   - PARTITION BY DAY enables efficient time-based queries
--   - DEDUP on (timestamp, position_id) prevents duplicate position inserts
--   - UPDATE queries (position_updated, position_closed) modify current_price and P&L


-- ============================================================================
-- VERIFICATION QUERIES
-- ============================================================================

-- Check that all tables were created
SELECT table_name, designatedTimestamp, partitionBy, walEnabled, dedup
FROM tables()
WHERE table_name IN ('strategy_signals', 'orders', 'positions')
ORDER BY table_name;

-- Check table schemas
SELECT table_name, column_name, column_type, is_symbol, is_designated
FROM table_columns('strategy_signals')
ORDER BY column_name;

SELECT table_name, column_name, column_type, is_symbol, is_designated
FROM table_columns('orders')
ORDER BY column_name;

SELECT table_name, column_name, column_type, is_symbol, is_designated
FROM table_columns('positions')
ORDER BY column_name;

-- Check table sizes (should be empty initially)
SELECT 'strategy_signals' as table_name, count(*) as row_count FROM strategy_signals
UNION ALL
SELECT 'orders' as table_name, count(*) as row_count FROM orders
UNION ALL
SELECT 'positions' as table_name, count(*) as row_count FROM positions;


-- ============================================================================
-- MIGRATION NOTES
-- ============================================================================

/*
SCHEMA CHANGES from migration 001:

1. strategy_signals:
   - ADDED: signal_id STRING (unique identifier for DEDUP)
   - ADDED: session_id SYMBOL (backtesting correlation)
   - IMPROVED: DEDUP UPSERT KEYS(timestamp, signal_id)

2. orders:
   - ADDED: session_id SYMBOL (backtesting correlation)
   - IMPROVED: DEDUP UPSERT KEYS(timestamp, order_id)

3. positions:
   - ADDED: session_id SYMBOL (backtesting correlation)
   - IMPROVED: DEDUP UPSERT KEYS(timestamp, position_id)

COMPATIBILITY with TradingPersistenceService:

✓ strategy_signals INSERT: All columns match (signal_id optional, session_id optional)
✓ orders INSERT: All columns match (session_id optional)
✓ positions INSERT: All columns match (session_id optional)
✓ UPDATE queries: Compatible (order_filled, order_cancelled, position_updated, position_closed)

MIGRATION STRATEGY:

1. Run migration: python database/questdb/install_questdb.py
2. Verify tables: SELECT table_name FROM tables() WHERE table_name IN ('strategy_signals', 'orders', 'positions');
3. Update TradingPersistenceService to populate signal_id and session_id (future enhancement)
4. Wire TradingPersistenceService to EventBus in container
5. Test with paper trading mode first
6. Enable for live trading

ROLLBACK PLAN:

If migration needs to be rolled back:
  DROP TABLE IF EXISTS strategy_signals;
  DROP TABLE IF EXISTS orders;
  DROP TABLE IF EXISTS positions;

Note: This will delete all trading data. Backup before rollback if needed.
*/

-- ============================================================================
-- END OF MIGRATION
-- ============================================================================
