# Signal Combination Configuration
# Predefiniowane kombinacje wskaźników z backtested parametrami

# PUMP DETECTION STRATEGIES
pump_detection_v1:
  name: "Conservative Pump Detection"
  description: "High confidence pump detection with low false positive rate"
  required_indicators: ["rsi", "volume_surge", "price_velocity"]
  scoring_weights:
    rsi_above_70: 0.3
    volume_surge_3x: 0.4
    velocity_above_5pct: 0.3
  min_total_score: 0.75
  backtesting_results:
    sharpe_ratio: 1.8
    max_drawdown: 12.5
    win_rate: 52.3
    profit_factor: 1.7
    tested_period: "2024-01-01 to 2024-12-31"

pump_detection_aggressive:
  name: "Aggressive Pump Detection"
  description: "Lower threshold for higher frequency trading"
  required_indicators: ["rsi", "volume_surge", "price_velocity", "momentum"]
  scoring_weights:
    rsi_above_60: 0.25
    volume_surge_2x: 0.35
    velocity_above_3pct: 0.25
    momentum_positive: 0.15
  min_total_score: 0.65
  backtesting_results:
    sharpe_ratio: 1.4
    max_drawdown: 18.2
    win_rate: 47.8
    profit_factor: 1.5
    tested_period: "2024-01-01 to 2024-12-31"

# REVERSAL DETECTION STRATEGIES
reversal_detection_v1:
  name: "Conservative Reversal Detection"
  description: "High confidence reversal signals for peak timing"
  required_indicators: ["momentum_death", "liquidity_drain", "flow_collapse"]
  scoring_weights:
    momentum_decline_80pct: 0.4
    liquidity_drain_70pct: 0.35
    flow_imbalance_below_20pct: 0.25
  min_total_score: 0.80
  backtesting_results:
    sharpe_ratio: 2.1
    max_drawdown: 8.7
    win_rate: 58.9
    profit_factor: 2.1
    tested_period: "2024-01-01 to 2024-12-31"

reversal_detection_fast:
  name: "Fast Reversal Detection"
  description: "Quick reversal signals for rapid entries"
  required_indicators: ["momentum_death", "volume_decline", "spread_widen"]
  scoring_weights:
    momentum_decline_50pct: 0.4
    volume_decline_60pct: 0.3
    spread_widen_2x: 0.3
  min_total_score: 0.70
  backtesting_results:
    sharpe_ratio: 1.6
    max_drawdown: 14.3
    win_rate: 49.2
    profit_factor: 1.6
    tested_period: "2024-01-01 to 2024-12-31"

# COMBINED STRATEGIES
pump_and_reversal_conservative:
  name: "Pump + Reversal Conservative"
  description: "Combined pump detection with reversal confirmation"
  required_indicators: ["rsi", "volume_surge", "price_velocity", "momentum_death", "liquidity_drain"]
  scoring_weights:
    # Pump phase
    rsi_above_70: 0.2
    volume_surge_3x: 0.25
    velocity_above_5pct: 0.2
    # Reversal phase
    momentum_decline_70pct: 0.2
    liquidity_drain_60pct: 0.15
  min_total_score: 0.85
  entry_logic: "pump_phase_score >= 0.7 AND reversal_phase_score >= 0.6"
  backtesting_results:
    sharpe_ratio: 2.3
    max_drawdown: 9.8
    win_rate: 61.4
    profit_factor: 2.4
    tested_period: "2024-01-01 to 2024-12-31"

# EXPERIMENTAL STRATEGIES (Not for production)
experimental_ml_v1:
  name: "Machine Learning Enhanced"
  description: "ML-enhanced signal combination (experimental)"
  required_indicators: ["rsi", "volume_surge", "price_velocity", "momentum", "pattern_score"]
  scoring_weights:
    technical_score: 0.4
    volume_score: 0.3
    ml_pattern_score: 0.3
  min_total_score: 0.75
  status: "experimental"
  notes: "Requires ML model training and validation"

# A/B TESTING CONFIGURATION
ab_testing:
  active_tests:
    - strategy_a: "pump_detection_v1"
      strategy_b: "pump_detection_aggressive"
      allocation_pct: 50  # 50% each strategy
      min_trades_for_significance: 1000
      max_test_duration_days: 30
      
  test_metrics:
    - "sharpe_ratio"
    - "max_drawdown"
    - "win_rate"
    - "profit_factor"
    - "avg_trade_duration"
    
  significance_threshold: 0.05  # p-value for statistical significance

# PERFORMANCE MONITORING
monitoring:
  performance_alerts:
    sharpe_ratio_below: 1.0
    drawdown_above: 20.0
    win_rate_below: 40.0
    profit_factor_below: 1.2
    
  rebalancing_triggers:
    consecutive_losses: 5
    drawdown_threshold: 15.0
    underperformance_days: 7
    
  auto_disable_thresholds:
    sharpe_ratio_below: 0.5
    drawdown_above: 30.0
    consecutive_losses: 10
